version: '3.8'

services:
  backend:
    build: ./backend
    # ports: - "5001:5001" # Backend is now internal only
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - ./backend/instance:/app/instance # Persist DB

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80" # Map host 3000 to container 80 (nginx)
    depends_on:
      - backend
